# Generated by Django 4.2.7 on 2023-12-05 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_customuser_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='cart',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
